### ISSUE TITLE
Incorporate data storage into cluster

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#105]
Maybe send a survey to find out what users really need.

**Comment by gqqnbig** [comment]
[集群数据备份需求调查（回复）.xlsx](https://github.com/gqqnbig/shine-cluster/files/8443258/default.xlsx)

What do we get from this?

@wulamao @Lu-MPI

**Comment by Lu-MPI** [comment]
看起来用户只是勾选了所有可能的选项。

磁盘损坏：RAID，我们已经这样做了。

误删除、修改：版本控制系统，部署一个Git Server？ GitLab什么的……

容灾：异地数据备份？可行性低。

数据可访问性：
只有Synology空间大，shared空间太小以至于 #115 。
如果开始用Synology，任何计算服务下线都不影响Synology。基本满足高可用需求。Synology的高可用需要另一个Synology。

另一个idea：
如果提供Git Server，并只对部分数据保证高可用（如 Synology 挂了依然可访问代码和重要数据），
问题就转化成了：如何构建一个高可用的Git Server， 比如 https://chegva.com/3234.html

另外，如果要搞 Git Server，不如把[code-server](https://github.com/coder/code-server)一起搞了？

**Comment by gqqnbig** [comment]
> 如何构建一个高可用的Git Server

为何不用github或gitlab，且它们是异地的 :smile: 。不用git的人，不管托管在本地还是托管在远程，都不会用git。

**Comment by gqqnbig** [comment]
@luoyuqi-lab

**Comment by luoyuqi-lab** [comment]
看起来问卷数据没有什么价值，并且好像参与的人也不多，还有不少没在使用集群的朋友回答了。

我认为使用版本控制系统是个好主意，比如之前Qiu误删了文件要找回来就很麻烦。但是我不了解怎么部署，并且用户愿不愿意用。

误删文件或者想回退版本可能是users比较关心的问题。

**Comment by gqqnbig** [comment]
与 @wulamao 讨论了。

## 问卷调查

有些参与者没有注意到“全填3分意味着全都是0分。服务器管理员没有能力实现所有需求。”的要求。但我们处理回复的时候不把3分改为0分了，而是删除，因为3分改为0分会削弱一开始就打0分的人的权重，不公平。

![EXCEL_wqfQ6V6asd](https://user-images.githubusercontent.com/614159/162886590-98191155-7b17-45e4-b962-55e01f086b57.png)

有集群账号的人最关注服务器维护的情况，其次是物理磁盘损坏。

![EXCEL_cTA1uiFGZu](https://user-images.githubusercontent.com/614159/162886787-511caed7-4383-4244-8546-a248efb2f755.png)

没有集群账号的人关注误删除、服务器维护和物理磁盘损坏。

我们着重处理有集群账号的人的需求。

## Road map

1. 登录。目前的登陆节点是aha，这是单点故障。如果aha停机维护，用户无法访问数据和计算节点。
我们会提供后备登录节点，当aha需要停机维护时，用户可以通过后备登录节点访问数据和计算节点。这个行动项目回应问卷调查的“服务器维护”需求。
3. 数据。目前的数据存储全都保存在aha上，也是单点故障。我们准备用glusterfs之类的distributed file system。这个行动项目回应问卷调查的“服务器维护”需求。
wulamao 提到每种数据本身的性质不同，如数据集大，但可以从网上重新下载；个人的代码、log、计算结果size小，但比较珍贵。

我们会尝试提供两个文件夹，类似如下：

/shared1：该文件夹大，但不是高可用。
/shared2：该文件夹小，但高可用。

**Comment by gqqnbig** [comment]
sub-issue #110, #94
