### ISSUE TITLE
deploy backup node for aha

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#110]
try a VM on bespin

When aha is down, people can use this node.

**Comment by gqqnbig** [comment]
Then would we like to use slurmdbd? If so, slurmdbd is still single point of failure on aha.

**Comment by gqqnbig** [comment]
Tentative test schedule:

- [ ] Send email to the general public on the Aloha test.
- [ ] Starting from May 9, the general public can log in to Aloha.
- [ ] On May 16 one day only, disallow SSH login on Aha to simulate Aha down. Force users to log in to Aloha on that day. After 16th, reenable Aha.
- [ ] On May 23 and 24, disallow SSH login on Aha to simulate Aha down. Force users to log in to Aloha on that two days. After 24th, reenable Aha.

@luoyuqi-lab could you be in charge of the test schedule? All questions go to you.

**Comment by gqqnbig** [comment]
also, kick off logged-in users please.

**Comment by luoyuqi-lab** [comment]
To deny normal users' login on May 16, I will use the PAM module to restrict only sudoer can login.

1. Create a group login file, `sudo vim /etc/group.login.allowed`, then write root and sudo in it.

![image](https://user-images.githubusercontent.com/57832734/168228505-3c95cac4-dd46-491d-a57d-15f90d9bda9f.png)

2. Use PAM to achieve, `sudo vim /etc/pam.d/common-auth`, on the top, input:

`auth required pam_listfile.so onerr=fail item=group sense=allow file=/etc/login.group.allowed`

![image](https://user-images.githubusercontent.com/57832734/168229186-18304c14-2b86-400a-9054-9497622ccabf.png)

3. For kick off users, use `who`, `sudo -s` and `pkill -kill -t tty`.

I use my own Linux and multiple users to test it is OK, but unfortunately, it can not show some information to users why they can not log in, it's the future work.

**Comment by luoyuqi-lab** [comment]
Unfortunately, the method does not work by PAM, I have no idea about this now.

So I use another method from SSH:

1.`sudo vim /etc/ssh/sshd_config`

2.Add the following line,

`AllowGroups root sudo`

3.`sudo systemctl restart sshd`

Now normal users can not log in by their Key, they must input the password that actually they have no.

I ask some normal users to help me test. It works now.
