### ISSUE TITLE
服务器安装是否要创建脚本？

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#112]
https://github.com/gqqnbig/shine-cluster/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85/_compare/5f33ddbcfeba78f16a952ddb7b73914246aef7ad...dfe82cb9f973a0344811bdafbdee4816757ca40e

原来的代码复制粘贴到命令行就会运行，而现在需要先创建脚本，复制粘贴，再运行。

请检查一下创建脚本是否必要，为什么不能交互式运行。

**Comment by gqqnbig** [comment]
如果创建脚本是因为#91 "把它们变成一个脚本或文件，用PR的方式提交"。请尽快发起PR。

**Comment by willwu-mpi** [comment]
首先需要评估工作量以及复杂度。
如果量大且复杂度高，创建脚本是必要的，方便后面自动添加新的节点和维护。
如果目前工作量不大，复杂度较低，可以考虑交互式运行。

**Comment by gqqnbig** [comment]
Before dfe82cb9f973a0344811bdafbdee4816757ca40e,  the syntax `$arr[@]` is zsh-specific. To make it work in Bash, `${arr[@]}` should be used.

@wulamao Found the code before dfe82cb9f973a0344811bdafbdee4816757ca40e didn't work in his zsh neither.
His zsh loads no configuration, ie. `zsh --no-rcs`. He reported the comment didn't work. 
This is because `INTERACTIVE_COMMENTS` is off by default in zsh, on in bash. Oh my zsh turned this on.
