### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#117]
Run `sudo journalctl -u uwsgi-registration` you will see

> Apr 06 10:43:14 aha uwsgi[1697]: b"... Host key verification failed ..."

When I manually run 
```console
$ ssh dagobah
The authenticity of host 'dagobah (172.25.17.17)' can't be established.
ECDSA key fingerprint is SHA256:aTwoSJspgke/2jp7HJz9ffJokweTRVZTudOhPTFqcqU.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

Therefore somehow the fingerprint  of dagobah is not recognized by aha, so [cluster-add-user/cluster-add-user.sh](https://github.com/gqqnbig/shine-cluster/blob/master/cluster-add-user/cluster-add-user.sh) failed to create account on dagobah.

**Comment by gqqnbig** [comment]
有两种方法。

1. `ssh -o StrictHostKeyChecking=no dagobah` 会自动信任远程主机的host key，不进行host key verification。
2. 把远程主机的host key预先加到账户中。

方法1比较简单。但如果有人在aha和dagobah（及其他compute nodes）之间进行man-in-the-middle attack，这个方法直接信任了远程主机，所以无法发现man-in-the-middle attack，似乎有安全问题。

方法2需要预先知道所有compute nodes的host key。Each machine has 3 host keys in 3 formats，3种key都需要存进git。这些key是public key，其对应的private key则需要另外保存，比较麻烦。另外机器重装后，我们要导入private key and public key。

方法2还有一个好处。用户第一次连接服务器时，putty或其他客户端会进行host key verification。

![putty_jfx6AGKhL8](https://user-images.githubusercontent.com/614159/165293135-8631e9b7-181a-482f-ae3a-ff16659a2aeb.png)

我们既然记录公开所有host (public) key，用户就可以比对putty提示的host key是不是和我们声明的一样。目前我们没有这样的设施，用户只能盲目地按accept。

**Comment by gqqnbig** [comment]
@wulamao @luoyuqi-lab 我们用哪种方法？

**Comment by luoyuqi-lab** [comment]
我查阅了下资料，1的方法一般是用在内网测试时候使用，感觉也不是长久之计。

如果2只是需要重复性工作的话，也许我们可以抽时间来完成。

**Comment by gqqnbig** [comment]
I see @luoyuqi-lab as inclining to option 2. Every time a machine reinstalls or we reconfigure SSH, we have to either import back the original host keys or record the newly generated. This route is not a one-time work, but of course leads to an ongoing safety.

**Comment by Lu-MPI** [comment]
指纹提示应该只会出现一次，确认之后不应该出现多次？

如果多次出现是否有类似“Failed to add the host to the list of known hosts ”之类的提示？

显式的SSH应当只发生在：用户-Aha，和Aha-其他。Aha显式的连接过一次其他服务器就应该会有完整的known hosts了吧？

**Comment by gqqnbig** [comment]
Discussed with @Lu-MPI , we do option 1 first. We can have someone to record all host keys. If that guy can update all host keys in time whenever a machine is reinstalled or reconfigured, we can then switch to option 2.

**Comment by gqqnbig** [comment]
> 如果2只是需要重复性工作的话，也许我们可以抽时间来完成。

If you want to do anything, create a separate issue, then close this issue. Otherwise just close this issue.
