### ISSUE TITLE
Add Hoth to cluster

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#122]

**Comment by gqqnbig** [comment]
https://github.com/gqqnbig/shine-cluster/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85#%E6%A3%80%E6%9F%A5%E7%A1%AC%E7%9B%98%E5%88%86%E5%8C%BA

请先完成到“检查硬盘分区”，然后assign给我。

**Comment by luoyuqi-lab** [comment]
It seems hoth is OK. @gqqnbig 

![image](https://user-images.githubusercontent.com/57832734/165891845-142055df-4c30-45f4-8782-504ddd53d4e3.png)

**Comment by gqqnbig** [comment]
已完成 https://github.com/gqqnbig/shine-cluster/wiki/GPU%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85 的“安装软件”步骤。但conda没装。

请研究nvidia driver版本要高一点还是低一点，the pros and cons。

**Comment by luoyuqi-lab** [comment]
Hoth now： 

`NVIDIA-SMI 470.103.01     Driver Version: 470.103.01     CUDA Version: 11.4`

**Comment by luoyuqi-lab** [comment]
我倾向于把hoth从470升级到510版本。

1.目前RTX8000官方驱动给到了510。

2.我并没有查找到在470和510之间的巨大性能差距，或者510的disadvantage，少量470更好的信息是针对于家用显卡以及游戏表现的。

3.关于CUDA版本，CUDA11版本之后兼容性都很好，不用担心11.4和11.6会有什么影响。[Click here to view.](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#use-the-right-compat-package)

4.更新的版本可能意味着low stability，但是我认为是可控的并且回退版本是能做到的。并且目前最新的是515版本。

5.所有计算节点统一到510版本更利于之后的统一更新和debug。

Lu也更倾向于新的，因为他报告说之前某些老版本的英伟达驱动会导致tensorflow需要import10分钟以上，并且建更新后测试tensorflow是否正常。

@gqqnbig What’s your opinion?

**Comment by gqqnbig** [comment]
go ahead with Hoth.

Are you gonna manually install the driver ?

Write down your steps, and I will take care of the other server.

**Comment by luoyuqi-lab** [comment]
1. `ubuntu-drivers devices`，查找适合的包。

  ![image](https://user-images.githubusercontent.com/57832734/187348187-a6d9c649-fb9f-4e5b-a63b-c94caeca7aa1.png)

2. `sudo apt install nvidia-driver-510-server`，安装驱动。

3. 安装后调用nvidia-smi失败。提示“NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. ”

4. 用`ls /usr/src | grep nvidia`查看发现确实装好了  

![image](https://user-images.githubusercontent.com/57832734/187351187-a7a4c906-cfe1-4608-89d9-ea3782541683.png)

5. `sudo apt-get install dkms`, ` sudo dkms install -m nvidia-srv -v 510.85.02`。

6. ‘sudo reboot’，问题解决，驱动升级成功。

![image](https://user-images.githubusercontent.com/57832734/187351449-2f463a99-06e4-4d2d-9507-9e8a80ba7cf3.png)

**Comment by luoyuqi-lab** [comment]
conda安装完成，follow [Wiki](https://github.com/gqqnbig/shine-cluster/wiki/GPU%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85).
![image](https://user-images.githubusercontent.com/57832734/187364305-1713e6e6-1ca7-4767-8695-c6cd5bf847b3.png)

**Comment by luoyuqi-lab** [comment]
slurm安装
1. 安装[随机gpu工具](https://github.com/gqqnbig/shine-cluster/wiki/%E5%AE%89%E8%A3%85slurm%E5%AE%A2%E6%88%B7%E7%AB%AF#slurm%E7%9B%B8%E5%85%B3%E5%B7%A5%E5%85%B7). 遇到权限问题可以用root在正确目录解决。[Issue](https://github.com/gqqnbig/randomize-gpu/issues/1).
2. Follow [Wiki](https://github.com/gqqnbig/shine-cluster/wiki/%E5%8D%95%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88GPU%EF%BC%89%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6).
3. 如果遇到github unsafe的错误，按照错误提示运行`git config --global --add safe.directory /shine-cluster`
4. 修改添加hoth中`/etc/slurm-llnl`的文件，参照其他计算节点的文件映射，用`ln`添加。`sudo ln -s /shine-cluster/slurm/etc/slurm/slurm.conf /etc/slurm-llnl/`, `sudo ln -s /shine-cluster/slurm/etc/slurm/cgroup.conf /etc/slurm-llnl/cgroup.conf`
5. 修改`/etc/slurm-llnl/slurm.conf`配置，末尾加入hoth的信息。
6. 修改`vim /etc/hosts`, 内容复制别的节点。
7. [资料](https://webcache.googleusercontent.com/search?q=cache:X88z7xSF1cIJ:https://gqqnbig.me/2021/01/27/slurm%25E5%258D%2595%25E6%259C%25BA%25E6%259C%2580%25E7%25AE%2580%25E5%25AE%2589%25E8%25A3%2585%25E5%2585%25A8%25E7%2590%2583%25E6%259C%2580%25E8%25AF%25A6%25E7%25BB%2586%25E6%2595%2599%25E7%25A8%258B/&cd=4&hl=zh-CN&ct=clnk)
8. `sudo slurmctld -c -D`
9. 从aha的`etc/munge`拷贝munge.key文件，放到hoth的同路径。
10. aha的slurm.conf也需要修改。
11. aha重启slurm，`sudo systemctl restart slurmctld`

**Comment by gqqnbig** [comment]
> 5\. `sudo apt-get install dkms`, ` sudo dkms install -m nvidia-srv -v 510.85.02`。

Try to install the driver from https://www.nvidia.com/Download/index.aspx?lang=en-us

Write if it works without dkms

**Comment by gqqnbig** [comment]
> 2\. Follow Wiki.

I want to delete the page 单服务器（GPU）资源调度. To start with, it doesn't say how to make sure cgroups works, and what the error message is. Moverover, we don't need to run slurmctld or munged --force. Last but not least, most if not all useful and verified content has been distributed over to other pages.

**Comment by gqqnbig** [comment]
By and large, I'm delighted to see you uncovered these bugs and so many undocumented steps in this project that we the creators have neglected. Good job, Yuqi!

**Comment by luoyuqi-lab** [comment]
> > 5. `sudo apt-get install dkms`, ` sudo dkms install -m nvidia-srv -v 510.85.02`。
> 
> Try to install the driver from https://www.nvidia.com/Download/index.aspx?lang=en-us
> 
> Write down if it works without dkms



> > 5. `sudo apt-get install dkms`, ` sudo dkms install -m nvidia-srv -v 510.85.02`。
> 
> Try to install the driver from https://www.nvidia.com/Download/index.aspx?lang=en-us
> 
> Write down if it works without dkms

I‘m afraid it is hard to be installed. In the beginning I indeed by this method, the package is still in the hoth. But there are too many bugs to install the driver manually and it's hard for me to solve them and install the NVidia driver after I try some guide but doesn't work. So at last I use apt-get to auto-install. Then we meet the dkms problem.

**Comment by luoyuqi-lab** [comment]
Add normal users by [Wiki](https://github.com/gqqnbig/shine-cluster/wiki/%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86#%E5%A4%8D%E5%88%B6%E7%94%A8%E6%88%B7%E5%88%B0%E8%AE%A1%E7%AE%97%E8%8A%82%E7%82%B9)

**Comment by luoyuqi-lab** [comment]
I also find Aloha's slurm.conf is not updated so some users can not link hoth by **aloha**.

I use smartgit and cherry pick to change slurm.conf.

BTW, the smartgit cannot open shine-cluster because Permission. Use `sudo chown -R qiqig:sudo /shine-cluster/
` to solve.

Now aloha can normally connect with hoth.

@gqqnbig Can you have a look? I'd like to close this issue.

**Comment by gqqnbig** [comment]
The issue creator closes an issue, not you. 

Yet, you haven't made a PR.
