### ISSUE TITLE
Share common applications among nodes

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#126]
Each compute node must have an anaconda binary. Each machine installing its own anaconda is wasteful.

I propose to use nfs that shares one conda binary to all compute nodes.

<pre>
Tatooine /opt     \
                   -> anaconda
Dagobah /opt      /

Tatooine /opt-all      \
                        \
Dagobah /opt-all         --> Smartgit, Beyond Compare, or Pycharm
                        /
Aha /opt-all           /
</pre>

On Tatooine and Dagobah, as they are compute nodes, their `/opt` has anaconda. On all nodes, their `/opt-all` has common applications including Smartgit, Beyond Compare, or Pycharm.

[/opt](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s13.html) is the standard place for add-on application software packages. But is /opt-all ok? Any other idea?

TODO:
- [ ]  update https://github.com/gqqnbig/shine-cluster/wiki/GPU%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85

**Comment by gqqnbig** [comment]
[ ] update https://github.com/gqqnbig/shine-cluster/wiki/GPU%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85

**Comment by gqqnbig** [comment]
I will use the technique of #93

**Comment by gqqnbig** [comment]
Your opinion please

**Comment by wulamao** [comment]
由于该提议的技术实现并不是瓶颈，因此我们主要该更新带来的影响。
优势：
1. 更新软件，维护服务，更加方便
2. 能节省一定的磁盘空间

额外的影响：
1. 增加了应用程序对网络，对NFS服务的依赖关系
2. 对于应用程序性能的影响（暂时无法评估）
3. 实现该更新需要花费的时间（由负责更新功能的同学来评估）

总之，我认为是一个很好的尝试，在初期对服务器运行影响较小， @gqqnbig 你觉得呢？
另外， 或许使用 /opt-sharing-all？opt-sharing-xx，第三个xx代表共享的类别？只是一个提议，仅供参考。

**Comment by gqqnbig** [comment]
sharing是实现方式。用户不需要关心实现方式。这与~/shared不同。

I go with /opt and /opt-all.

**Comment by gqqnbig** [comment]
@luoyuqi-lab Your #122 depends on this issue. Yet you don't want to build on sand.

Since I made the PR, I can't review my own. Can you or can you have someone review #133?

**Comment by gqqnbig** [comment]
Exporting file system is done. Mounting file system is in issue #149, #150.
