### ISSUE TITLE
进入后台作业，srun --jobid每次都失败？

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#142]
https://github.com/gqqnbig/shine-cluster/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97%EF%BC%9A%E7%94%A8SLURM%E8%BF%90%E8%A1%8C%E8%AE%A1%E7%AE%97%E4%BB%BB%E5%8A%A1

```bash
qiqig@aha:~$ srun --jobid 483   
# will: 如果上述方式失败，请尝试srun --jobid=483 --pty /bin/bash
```

请问`srun --jobid 483`何时成功何时失败，如果每次都失败，就不要把错误写法留着了。

**Comment by Lu-233** [comment]
是的，这样每次都会失败，因为没有给出要执行的命令

可以用will的命令替代原来的。

**Comment by gqqnbig** [comment]
Fixed in https://github.com/gqqnbig/shine-cluster/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97%EF%BC%9A%E7%94%A8SLURM%E8%BF%90%E8%A1%8C%E8%AE%A1%E7%AE%97%E4%BB%BB%E5%8A%A1/_compare/8ed9a923bc6f58962d1feba863d8a89b5d004269...4acb11ca8658bd90552dd670b011e5157178c51f
