### ISSUE TITLE
How long will the server cluster could restored to use?

### ISSUE THREAD

**Issue by o0mahan0o** [gqqnbig/shine-cluster#163]
When I try to log in to the server, I got:

[13:49:41.025] Server installation process already in progress - waiting and retrying
[13:49:41.025] Terminating local server

I found this problem yesterday night, but it still can not use by now.
I wonder if this problem is caused by network change and when the server will be restored.
Thanks.

**Comment by wulamao** [comment]
It may have arisen from the disk limitation, pls check it.

**Comment by gqqnbig** [comment]
https://github.com/gqqnbig/shine-cluster/wiki/%E9%9B%86%E7%BE%A4%E7%AE%80%E4%BB%8B#user-requirements

> 集群仅支持使用Putty和OpenSSH命令行登录。其他方式可能可以登录，但不保证后续不会出错。

如果是VS Code报错的话，shine-cluster不提供技术支持。

本issue将会被关闭，但关闭后VS Code的爱好者还是可以继续讨论如何用VS Code解决问题。

如果Putty和OpenSSH命令行登录报错，请另开一个issue。

**Comment by o0mahan0o** [comment]
> It may have arisen from the disk limitation, pls check it. The question is similar to https://stackoverflow.com/questions/64298741/vs-code-ssh-remote-connection-issues/69552450, and Konfido given the answers.

That's right!  William helped me find the cause of the problem. It is really that my disk usage space exceeds the upper limit. After cleaning, it has returned to normal. Thanks a lot.
