### ISSUE TITLE
Try containers

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#22]
https://www.reddit.com/r/docker/comments/7y2yp2/why_is_singularity_used_as_opposed_to_docker_in/

https://tin6150.github.io/psg/blogger_container_hpc.html

**Comment by gqqnbig** [comment]
docker

running dokcer means he has root.

shifter
has native slurm support

**Comment by gqqnbig** [comment]
docker or LXD cannot hide host CPU or hardware from guest os. [ref 1](https://discuss.linuxcontainers.org/t/how-to-hide-of-host-root-device-from-container-lsblk/6103) [ref 2](https://lxc-users.linuxcontainers.narkive.com/HWiuyMQQ/restricting-container-visible-cpus)

**Comment by gqqnbig** [comment]
No rootfull docker. Docker is too easy to mess up with the network interfaces. Rootful docker also has potential to cause kernel errors.

**Comment by gqqnbig** [comment]
Please verify if docker works. Or let me know it's no longer needed.

**Comment by Lu-MPI** [comment]
我尝试了rootless docker，目前看一切正常。

包括：
- 下载、删除镜像
- 构建、删除、启动和停止容器
- 安装包（texlive 和 latex2html）
- 运行命令
- 挂载主机目录，使用程序进行读写
