### ISSUE TITLE
If cluster-add-user.sh cannot create account on compute node, give a notice

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#70]
Incident:

violet created the cluster account, when she logged into Eureka, the account on Eureka is qiqigtest.

Investigation:

https://github.com/gqqnbig/mpi-servers/blob/469746306beef2b329091db90531fe80f9cb67e8/cluster-add-user/cluster-add-user.sh#L72-L79

If cluster-add-user.sh cannot create account on compute node, it gives an output. The whole process exits with no error.

https://github.com/gqqnbig/email-registration/blob/ee0d207be3edae6e31408cc712d3a3a68ea74191/src/Registration/django/web/view.py#L106-L110

email-registration calls cluster-add-user.sh. Since cluster-add-user.sh  exits with no error, the except part does not run, and users or admins don't know an issue happened, neither the issue is logged.

**Comment by gqqnbig** [comment]
For the record, corss repo embedded code snippets do not work.

**Comment by gqqnbig** [comment]
block future registerion

**Comment by gqqnbig** [comment]
@wulamao @Lu-MPI I need your inputs

**Comment by Lu-MPI** [comment]
文件 ~/shared/remote-add-user 已经被创建了，这是cluster-add-user.sh创建的么？如果是，看起来之前的流程应该通过了。但是我查看Django项目的代码，setting中创建项目的命令CREATE_ACCOUNT是空字符串……

我评论时看用户列表，violet的账号已经被创建了，是bug发现后手动创建的吗？

所以目前的情况是否可以描述为：cluster-add-user.sh执行了remote-add-user但是没有创建用户？

可否在remote-add-user中添加log如前后用户列表的记录，再进行一个新用户测试，来确认remote-add-user是否被执行，和执行结果呢？

**Comment by gqqnbig** [comment]
Talked with @Lu-MPI , suggestion is to add `print(output)` after

https://github.com/gqqnbig/email-registration/blob/ee0d207be3edae6e31408cc712d3a3a68ea74191/src/Registration/django/web/view.py#L107

so that the output by remote-add-user is captured.

**Comment by gqqnbig** [comment]
Do on 12/12 if no other feedback or no push.

**Comment by Lu-MPI** [comment]
回想起来，这个issue开始是由于不同服务器上的用户不同引起的，因此在创建用户后可能导致冲突。

一个可以考虑的策略：创建用户时，在所有服务器上同步创建。 

另外，还提议检查服务器上现有的用户是否是同步的，以避免类似的bug产生。

**Comment by gqqnbig** [comment]
如果改用LDAP就不用处理此issue了。
Do after #78

**Comment by gqqnbig** [comment]
fixed by https://github.com/gqqnbig/email-registration/pull/2
