### ISSUE TITLE
Re-install Eureka

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#75]
Utilize the two disks in Eureka.

I suggest to combine the two disks into one logic disk unless the combined disk is too large.

**Comment by gqqnbig** [comment]
do on Jan 11

**Comment by Lu-MPI** [comment]
is it means raid0 or raid1 ?

**Comment by gqqnbig** [comment]
Compute nodes don't use RAID.

**Comment by Lu-MPI** [comment]
Eureka的重新安装是否遇到了什么Issue？

**Comment by gqqnbig** [comment]
defects reported
