### ISSUE TITLE
添加英语成语到每日提示

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/shine-cluster#84]
添加一个文件，里面有100个英语成语。

添加到 https://github.com/gqqnbig/mpi-servers/tree/master/login/etc/daily-tips

**Comment by gqqnbig** [comment]
Each tip shall include idiom, example, and explanation (in a format you like).

If it has one unfamiliar/advanced/new word, add Chinese.

Avoid to have more than one new word. If the example in the book has too many new words, you coin another example.

**Comment by gqqnbig** [comment]
done in #108

**Comment by gqqnbig** [comment]
@luoyuqi-lab 

For the linked PR, can you remove the idioms from other chapters? In other words, the idioms should go to the correct files.

Make a separate PR. 

You can just delete the wrong idioms. Don't worry about deleting your effort; they are still in Git history and I will pick them up later.

The book's on my desk.

Thank you.

**Comment by luoyuqi-lab** [comment]
Because in that time I ignore some very simple idioms so it is hard to achieve 100 idioms......

So I add some idioms from other chapters and some that I love.

Got your idea now and I will revise it.

@gqqnbig

**Comment by gqqnbig** [comment]
Don't remove your assignment. Currently the issue has no assignee, then who is responsible for it? Which PR or action can trigger the closure of this issue? No structural information is available.

Instead, because you were involved due to my comment

> @ luoyuqi-lab
> 
> For the linked PR, can you remove the idioms from other chapters

you assign the issue to me.

**Comment by gqqnbig** [comment]
@luoyuqi-lab  Another way is to add:

fixed in #135
