### ISSUE TITLE
Coruscant Fun is Tooooo Noisy

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/shine-cluster#87]
Coruscant 目前的噪音很大，另一台18也有类似的问题。

观察服务器发现，服务器风扇可能在全速运转。

用手感受后方出风口，只有在使用的两块显卡是热的。

我们也许可以控制服务器风扇的散热策略

如：https://askubuntu.com/questions/22108/how-to-control-fan-speed

**Comment by Lu-MPI** [comment]
看起来superdoctor可以查看和设置风扇

软件地址：https://www.supermicro.com/en/solutions/management-software/superdoctor

支持Linux，但看起来是申请的（下载地址在最后需要填表单）。

**Comment by Lu-MPI** [comment]
IPMI 的用户手册

https://www.supermicro.com/manuals/other/IPMI_Users_Guide.pdf

**Comment by gqqnbig** [comment]
Installed SuperDoctor 5.

![vivaldi_fmkkKa6ygh](https://user-images.githubusercontent.com/614159/148878547-84101ab1-24e8-4667-b8b2-32cae1a6f2c2.png)

It can read fan speed and set lowest speed, but no way to have other control.

![vivaldi_gPW4lZW7nC](https://user-images.githubusercontent.com/614159/148878644-184a5f46-ef70-4c02-a43a-6eca0638299a.png)

Power Control is for rebooting the device.

**Comment by Lu-MPI** [comment]
设置风扇模式：

1. 下载IPMICFG：https://www.supermicro.com/SwDownload/SwSelect_Free.aspx?cat=IPMI
2. 解压并将对应平台的可执行文件上传服务器（对于我们，是IPMICFG-Linux.x86_64）
3. chmod +x IPMICFG-Linux.x86_64
4. 查看风扇模式 `sudo ./IPMICFG-Linux.x86_64 -fun` 包括目前的模式和支持的模式
5. 修改风扇模式 `sudo ./IPMICFG-Linux.x86_64 -fun 2` 数字为模式代码

风扇模式目前在dagobah、coruscant上显示的有：
```
Supported Fan modes:
1:Full
2:Optimal
4:Heavy IO
```

如果风扇处于FULL模式，开机会有非常大的噪音。

**Comment by gqqnbig** [comment]
Can you find the URL of the zip file, use `wget` to download it, then use `unzip` to unzip it?

Thanks

**Comment by Lu-MPI** [comment]
无法给出wget可用的连接。

下载页面基于ASP.NET编写，需要手动点击接受协议，改变页面状态到下载，再点击按钮触发下载，这些操作由ASP.NET在同一页面托管，因此不支持wget的下载方式。

**Comment by gqqnbig** [comment]
Good job. I will take care of it from now on.

**Comment by gqqnbig** [comment]
需要分贝计

**Comment by gqqnbig** [comment]
shut off coruscant
